### ISSUE TITLE
server crash 

### ISSUE THREAD

**Issue by mmp** [mmp/vice#123]
This is a new one. I'm wondering if it's related to new versus old versions of the client (without RPCVersion bumped) In any case we shouldn't be panicing however...
```
panic: interface conversion: interface {} is int, not float64

goroutine 33735 [running]:
main.newWorld.func2({0xc012949a00, 0x4})
        /home/matt_pharr/vice/sim.go:975 +0x3b4
main.newWorld({{0xc0014a2480, 0xe}, 0xc009260870, {0xc012949884, 0x4}, 0xc0023f8d80, {0xc009cd9880, 0x1c}, 0x0, {0xc002d3384c, ...}, ...}, ...)
        /home/matt_pharr/vice/sim.go:1013 +0xc86
main.NewSim({{0xc0014a2480, 0xe}, 0xc009260870, {0xc012949884, 0x4}, 0xc0023f8d80, {0xc009cd9880, 0x1c}, 0x0, {0xc002d3384c, ...}, ...}, ...)
        /home/matt_pharr/vice/sim.go:875 +0xa70
main.(*SimManager).New(0xc007f5f700, 0x1?, 0xc0093f4528)
        /home/matt_pharr/vice/server.go:260 +0xc5
reflect.Value.call({0xc001a29f20?, 0xc00648a218?, 0xf8bb74?}, {0xd7ea7b, 0x4}, {0xc000403ef8, 0x3, 0x1000000069e?})
        /usr/local/go/src/reflect/value.go:596 +0xce5
reflect.Value.Call({0xc001a29f20?, 0xc00648a218?, 0xc000403ea0?}, {0xc000403ef8?, 0x10?, 0xceab60?})
        /usr/local/go/src/reflect/value.go:380 +0xb9
net/rpc.(*service).call(0xc000267380, 0xc000267340, 0xc00eff6aa8, 0xc00eff6ac0, 0xc007f5fb80, 0xc0016fa900, {0xce8ca0?, 0xc009256700?, 0xedb6a8?}, {0xc3f560, ...}, ...)
        /usr/local/go/src/net/rpc/server.go:381 +0x20e
created by net/rpc.(*Server).ServeCodec in goroutine 33599
        /usr/local/go/src/net/rpc/server.go:478 +0x3d7
```

**Comment by mmp** [comment]
It's this line:
```
                dir := weather[0].Wdir.(float64)
```
